### ISSUE TITLE
Pre-trained SegNet for Primate

### ISSUE THREAD

**Issue by GenMoat** [SIPEC-Animal-Data-Analysis/SIPEC#24]
Hi,

I am pretty new to running the DL pipeline. I am using the docker image to test on primate videos. I have tried to use
--segnet_path/home/nexus/mask_rcnn_primate_0119.h5 and/home/user/data/pretrained_networks/mask_rcnn_primate_0119.h5, but there are no such files. Is there no such pre-trained primate SegNet published or am I using the wrong path?

Many thanks

**Comment by damaggu** [comment]
Hi, you are right, I added the network to the dropbox, please try again.

**Comment by GenMoat** [comment]
> Hi, you are right, I added the network to the dropbox, please try again.

Thank you! It works now.
