### ISSUE TITLE
Clarification of segementation.py argument.s

### ISSUE THREAD

**Issue by JLC827** [SIPEC-Animal-Data-Analysis/SIPEC#29]
Hi,

Can I please get some clarification on the usage of some of the command line argument for segmentation.py?

--fraction

help states :
'fraction to use for training'

segmentation.py states :
'fraction : float
        Factor by which to decimate the training data points.'

I'm unclear on exactly what these mean. Does this relate to the fraction of training/evaluation data used to evaluate the model? Does this default to a reasonable value? I see from the code it defaults to None, so does this mean there will be no evaluation data, even when perform_evaluation=True?

--gpu

help states:
'filename of the video to be processed (has to be a
                        segmented one)'

Is this correct? The examples given simply set this to 0. Is this actually referring to the GPU number to be used?

Many thanks.

**Comment by damaggu** [comment]
@JLC827 Sorry for the late response. the --fraction flag can be used to reduce the size of the training data if you want to do an ablation study. Thanks for the GPU flag, that was indeed the wrong descriptor. I changed it.
