### ISSUE TITLE
Can I run SIPEC in macOS m1 MAX with arm GPUs?

### ISSUE THREAD

**Issue by jiekechoo** [SIPEC-Animal-Data-Analysis/SIPEC#31]
I don't have NVIDIA GPU, so can I run SIPEC in macOS m1 MAX env?
anyone can help me ?

thanks a lot.

**Comment by damaggu** [comment]
Hi, sorry I think at this point it is really hard to run the pipeline without a GPU. An alternative is to load the code and use it in a google colab notebook (https://colab.research.google.com), they offer free GPUs. Best, Markus
